import QRCode from 'qrcode';
import fs from 'fs';
import path from 'path';

interface MenuItem {
  name: string;
  price: string;
  description?: string;
}

interface MenuCategory {
  name: string;
  items: MenuItem[];
}

interface MenuData {
  restaurant: string;
  location: string;
  categories: MenuCategory[];
}

/**
 * Generate QR code PNG for menu URL
 */
export async function generateQRCode(slug: string): Promise<Buffer> {
  const url = `https://menusready.com/menu/${slug}`;
  
  const qrBuffer = await QRCode.toBuffer(url, {
    width: 512,
    margin: 2,
    color: {
      dark: '#000000',
      light: '#FFFFFF',
    },
  });
  
  return qrBuffer;
}

/**
 * Generate plain text version of menu
 */
export function generateTextMenu(menuData: MenuData): string {
  let text = `${menuData.restaurant}\n`;
  text += `${menuData.location}\n`;
  text += `${'='.repeat(50)}\n\n`;
  
  menuData.categories.forEach((category) => {
    text += `${category.name.toUpperCase()}\n`;
    text += `${'-'.repeat(category.name.length)}\n\n`;
    
    category.items.forEach((item) => {
      text += `${item.name}`;
      if (item.price) {
        text += ` — $${item.price}`;
      }
      text += `\n`;
      
      if (item.description) {
        text += `  ${item.description}\n`;
      }
      text += `\n`;
    });
    
    text += `\n`;
  });
  
  text += `\n${'='.repeat(50)}\n`;
  text += `Generated by Menus Ready\n`;
  text += `https://menusready.com\n`;
  
  return text;
}

/**
 * Load menu data from file system
 */
export function loadMenuData(slug: string): MenuData {
  const menuPath = path.join(process.cwd(), 'data', 'restaurants', slug, 'menu.json');
  const fileContent = fs.readFileSync(menuPath, 'utf-8');
  return JSON.parse(fileContent);
}

/**
 * Generate all deliverables for a restaurant
 */
export async function generateDeliverables(slug: string): Promise<{
  qrCode: Buffer;
  textMenu: string;
  pdfMenu: Buffer | null;
  imageMenu: Buffer | null;
}> {
  const menuData = loadMenuData(slug);
  
  // Generate QR code
  const qrCode = await generateQRCode(slug);
  
  // Generate text menu
  const textMenu = generateTextMenu(menuData);
  
  // TODO: Implement PDF generation (complex, requires puppeteer or react-pdf)
  const pdfMenu = null;
  
  // TODO: Implement image generation (requires PDF first)
  const imageMenu = null;
  
  return {
    qrCode,
    textMenu,
    pdfMenu,
    imageMenu,
  };
}
